package com.pcs.itmis.report.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import com.pcs.itmis.report.entity.ComplaintRegistrationReport;
import com.pcs.itmis.report.entity.ReportEntity;

@Repository
public interface ComplaintRegistrationReportRepository extends JpaRepository<ReportEntity, Long>{
	
	@Query(nativeQuery = true, value = "select "
			+ "SUM(v.district_case_decided_by_court) AS district_case_decided_by_court,"
			+ "SUM(v.district_case_prosecuted_by_court) AS district_case_prosecuted_by_court,"
			+ "SUM(v.tip_case_decided_by_court) AS tip_case_decided_by_court,"
			+ "SUM(v.tip_case_prosecuted_by_court) AS tip_case_prosecuted_by_court"
			+ " from complaint_registration_report_view v "
			+ " where v.fiscal_year = '2078-79' ")
	List<ComplaintRegistrationReport> getCumulativeReport();


	@Query(nativeQuery = true, value = "select "
			+ " SUM(v.cr_under47part1) AS cr_under47part1," 
			+ "SUM(v.brahmin_cr_about_disability_card) AS brahmin_cr_about_disability_card,"
			+ " SUM(v.brahmin_cr_beyond_jurisdiction) AS brahmin_cr_beyond_jurisdiction,"
			+ " SUM(v.brahmin_cr_relevant_institutions) AS brahmin_cr_relevant_institutions, " 
			+ "SUM(v.brahmin_cr_to_battery) AS brahmin_cr_to_battery,"
			+ " SUM(v.brahmin_cr_to_defamation) AS brahmin_cr_to_defamation," 
			+ " SUM(v.brahmin_cr_to_divorce) AS brahmin_cr_to_divorce, "
			+ "SUM(v.brahmin_cr_to_legal_aid_service) AS brahmin_cr_to_legal_aid_service," 
			+ " SUM(v.brahmin_cr_to_medical_institutions) AS brahmin_cr_to_medical_institutions,"
			+ " SUM(v.brahmin_cr_to_minors) AS brahmin_cr_to_minors, " 
			+ "SUM(v.brahmin_cr_to_psycho_socio_counselling) AS brahmin_cr_to_psycho_socio_counselling,"
			+ "SUM(v.brahmin_cr_to_senior_citizen) AS brahmin_cr_to_senior_citizen," 
			+ " SUM(v.brahmin_cr_to_wages) AS brahmin_cr_to_wages,"
			+ " SUM(v.brahmin_cr_under47part2) AS brahmin_cr_under47part2, " 
			+ "SUM(v.brahmin_ds_medication_under47part2) AS brahmin_ds_medication_under47part2,"
			+ "SUM(v.brahmin_ds_under47part1) AS brahmin_ds_under47part1,"
			+ "SUM(v.dalit_cr_about_disability_card) AS dalit_cr_about_disability_card,"
			+ " SUM(v.dalit_cr_beyond_jurisdiction) AS dalit_cr_beyond_jurisdiction,"
			+ " SUM(v.dalit_cr_relevant_institutions) AS dalit_cr_relevant_institutions, " 
			+ "SUM(v.dalit_cr_to_battery) AS dalit_cr_to_battery,"
			+ " SUM(v.dalit_cr_to_defamation) AS dalit_cr_to_defamation," 
			+ " SUM(v.dalit_cr_to_divorce) AS dalit_cr_to_divorce, "
			+ "SUM(v.dalit_cr_to_legal_aid_service) AS dalit_cr_to_legal_aid_service," 
			+ " SUM(v.dalit_cr_to_medical_institutions) AS dalit_cr_to_medical_institutions,"
			+ " SUM(v.dalit_cr_to_minors) AS dalit_cr_to_minors, " 
			+ "SUM(v.dalit_cr_to_psycho_socio_counselling) AS dalit_cr_to_psycho_socio_counselling,"
			+ "SUM(v.dalit_cr_to_senior_citizen) AS dalit_cr_to_senior_citizen," 
			+ " SUM(v.dalit_cr_to_wages) AS dalit_cr_to_wages,"
			+ " SUM(v.dalit_cr_under47part2) AS dalit_cr_under47part2, " 
			+ "SUM(v.dalit_ds_medication_under47part2) AS dalit_ds_medication_under47part2,"
			+ "SUM(v.dalit_ds_under47part1) AS dalit_ds_under47part1,"
			+ "SUM(v.ethnic_minorities_cr_about_disability_card) AS ethnic_minorities_cr_about_disability_card,"
			+ " SUM(v.ethnic_minorities_cr_beyond_jurisdiction) AS ethnic_minorities_cr_beyond_jurisdiction,"
			+ " SUM(v.ethnic_minorities_cr_relevant_institutions) AS ethnic_minorities_cr_relevant_institutions, " 
			+ "SUM(v.ethnic_minorities_cr_to_battery) AS ethnic_minorities_cr_to_battery,"
			+ " SUM(v.ethnic_minorities_cr_to_defamation) AS ethnic_minorities_cr_to_defamation," 
			+ " SUM(v.ethnic_minorities_cr_to_divorce) AS ethnic_minorities_cr_to_divorce, "
			+ "SUM(v.ethnic_minorities_cr_to_legal_aid_service) AS ethnic_minorities_cr_to_legal_aid_service," 
			+ " SUM(v.ethnic_minorities_cr_to_medical_institutions) AS ethnic_minorities_cr_to_medical_institutions,"
			+ " SUM(v.ethnic_minorities_cr_to_minors) AS ethnic_minorities_cr_to_minors, " 
			+ "SUM(v.ethnic_minorities_cr_to_psycho_socio_counselling) AS ethnic_minorities_cr_to_psycho_socio_counselling,"
			+ "SUM(v.ethnic_minorities_cr_to_senior_citizen) AS ethnic_minorities_cr_to_senior_citizen," 
			+ " SUM(v.ethnic_minorities_cr_to_wages) AS ethnic_minorities_cr_to_wages,"
			+ " SUM(v.ethnic_minorities_cr_under47part2) AS ethnic_minorities_cr_under47part2, " 
			+ "SUM(v.ethnic_minorities_ds_medication_under47part2) AS ethnic_minorities_ds_medication_under47part2,"
			+ "SUM(v.ethnic_minorities_ds_under47part1) AS ethnic_minorities_ds_under47part1,"
			+ "SUM(v.female_cr_about_disability_card) AS female_cr_about_disability_card,"
			+ " SUM(v.female_cr_beyond_jurisdiction) AS female_cr_beyond_jurisdiction,"
			+ " SUM(v.female_cr_relevant_institutions) AS female_cr_relevant_institutions, " 
			+ "SUM(v.female_cr_to_battery) AS female_cr_to_battery,"
			+ " SUM(v.female_cr_to_defamation) AS female_cr_to_defamation," 
			+ " SUM(v.female_cr_to_divorce) AS female_cr_to_divorce, "
			+ "SUM(v.female_cr_to_legal_aid_service) AS female_cr_to_legal_aid_service," 
			+ " SUM(v.female_cr_to_medical_institutions) AS female_cr_to_medical_institutions,"
			+ " SUM(v.female_cr_to_minors) AS female_cr_to_minors, " 
			+ "SUM(v.female_cr_to_psycho_socio_counselling) AS female_cr_to_psycho_socio_counselling,"
			+ "SUM(v.female_cr_to_senior_citizen) AS female_cr_to_senior_citizen," 
			+ " SUM(v.female_cr_to_wages) AS female_cr_to_wages,"
			+ " SUM(v.female_cr_under47part2) AS female_cr_under47part2, " 
			+ "SUM(v.female_ds_medication_under47part2) AS female_ds_medication_under47part2,"
			+ "SUM(v.female_ds_under47part1) AS female_ds_under47part1,"
			+ "SUM(v.janajati_cr_about_disability_card) AS janajati_cr_about_disability_card,"
			+ " SUM(v.janajati_cr_beyond_jurisdiction) AS janajati_cr_beyond_jurisdiction,"
			+ " SUM(v.janajati_cr_relevant_institutions) AS janajati_cr_relevant_institutions, " 
			+ "SUM(v.janajati_cr_to_battery) AS janajati_cr_to_battery,"
			+ " SUM(v.janajati_cr_to_defamation) AS janajati_cr_to_defamation," 
			+ " SUM(v.janajati_cr_to_divorce) AS janajati_cr_to_divorce, "
			+ "SUM(v.janajati_cr_to_legal_aid_service) AS janajati_cr_to_legal_aid_service," 
			+ " SUM(v.janajati_cr_to_medical_institutions) AS janajati_cr_to_medical_institutions,"
			+ " SUM(v.janajati_cr_to_minors) AS janajati_cr_to_minors, " 
			+ "SUM(v.janajati_cr_to_psycho_socio_counselling) AS janajati_cr_to_psycho_socio_counselling,"
			+ "SUM(v.janajati_cr_to_senior_citizen) AS janajati_cr_to_senior_citizen," 
			+ " SUM(v.janajati_cr_to_wages) AS janajati_cr_to_wages,"
			+ " SUM(v.janajati_cr_under47part2) AS janajati_cr_under47part2, " 
			+ "SUM(v.janajati_ds_medication_under47part2) AS janajati_ds_medication_under47part2,"
			+ "SUM(v.janajati_ds_under47part1) AS janajati_ds_under47part1,"
			+ "SUM(v.madhesi_cr_about_disability_card) AS madhesi_cr_about_disability_card,"
			+ " SUM(v.madhesi_cr_beyond_jurisdiction) AS madhesi_cr_beyond_jurisdiction,"
			+ " SUM(v.madhesi_cr_relevant_institutions) AS madhesi_cr_relevant_institutions, " 
			+ "SUM(v.madhesi_cr_to_battery) AS madhesi_cr_to_battery,"
			+ " SUM(v.madhesi_cr_to_defamation) AS madhesi_cr_to_defamation," 
			+ " SUM(v.madhesi_cr_to_divorce) AS madhesi_cr_to_divorce, "
			+ "SUM(v.madhesi_cr_to_legal_aid_service) AS madhesi_cr_to_legal_aid_service," 
			+ " SUM(v.madhesi_cr_to_medical_institutions) AS madhesi_cr_to_medical_institutions,"
			+ " SUM(v.madhesi_cr_to_minors) AS madhesi_cr_to_minors, " 
			+ "SUM(v.madhesi_cr_to_psycho_socio_counselling) AS madhesi_cr_to_psycho_socio_counselling,"
			+ "SUM(v.madhesi_cr_to_senior_citizen) AS madhesi_cr_to_senior_citizen," 
			+ " SUM(v.madhesi_cr_to_wages) AS madhesi_cr_to_wages,"
			+ " SUM(v.madhesi_cr_under47part2) AS madhesi_cr_under47part2, " 
			+ "SUM(v.madhesi_ds_medication_under47part2) AS madhesi_ds_medication_under47part2,"
			+ "SUM(v.madhesi_ds_under47part1) AS madhesi_ds_under47part1,"
			+ "SUM(v.male_cr_about_disability_card) AS male_cr_about_disability_card,"
			+ " SUM(v.male_cr_beyond_jurisdiction) AS male_cr_beyond_jurisdiction,"
			+ " SUM(v.male_cr_relevant_institutions) AS male_cr_relevant_institutions, " 
			+ "SUM(v.male_cr_to_battery) AS male_cr_to_battery,"
			+ " SUM(v.male_cr_to_defamation) AS male_cr_to_defamation," 
			+ " SUM(v.male_cr_to_divorce) AS male_cr_to_divorce, "
			+ "SUM(v.male_cr_to_legal_aid_service) AS male_cr_to_legal_aid_service," 
			+ " SUM(v.male_cr_to_medical_institutions) AS male_cr_to_medical_institutions,"
			+ " SUM(v.male_cr_to_minors) AS male_cr_to_minors, " 
			+ "SUM(v.male_cr_to_psycho_socio_counselling) AS male_cr_to_psycho_socio_counselling,"
			+ "SUM(v.male_cr_to_senior_citizen) AS male_cr_to_senior_citizen," 
			+ " SUM(v.male_cr_to_wages) AS male_cr_to_wages,"
			+ " SUM(v.male_cr_under47part2) AS male_cr_under47part2, " 
			+ "SUM(v.male_ds_medication_under47part2) AS male_ds_medication_under47part2,"
			+ "SUM(v.male_ds_under47part1) AS male_ds_under47part1,"
			+ "SUM(v.muslim_cr_about_disability_card) AS muslim_cr_about_disability_card,"
			+ " SUM(v.muslim_cr_beyond_jurisdiction) AS muslim_cr_beyond_jurisdiction,"
			+ " SUM(v.muslim_cr_relevant_institutions) AS muslim_cr_relevant_institutions, " 
			+ "SUM(v.muslim_cr_to_battery) AS muslim_cr_to_battery,"
			+ " SUM(v.muslim_cr_to_defamation) AS muslim_cr_to_defamation," 
			+ " SUM(v.muslim_cr_to_divorce) AS muslim_cr_to_divorce, "
			+ "SUM(v.muslim_cr_to_legal_aid_service) AS muslim_cr_to_legal_aid_service," 
			+ " SUM(v.muslim_cr_to_medical_institutions) AS muslim_cr_to_medical_institutions,"
			+ " SUM(v.muslim_cr_to_minors) AS muslim_cr_to_minors, " 
			+ "SUM(v.muslim_cr_to_psycho_socio_counselling) AS muslim_cr_to_psycho_socio_counselling,"
			+ "SUM(v.muslim_cr_to_senior_citizen) AS muslim_cr_to_senior_citizen," 
			+ " SUM(v.muslim_cr_to_wages) AS muslim_cr_to_wages,"
			+ " SUM(v.muslim_cr_under47part2) AS muslim_cr_under47part2, " 
			+ "SUM(v.muslim_ds_medication_under47part2) AS muslim_ds_medication_under47part2,"
			+ "SUM(v.muslim_ds_under47part1) AS muslim_ds_under47part1,"
			+ "SUM(v.others_cr_about_disability_card) AS others_cr_about_disability_card,"
			+ " SUM(v.others_cr_beyond_jurisdiction) AS others_cr_beyond_jurisdiction,"
			+ " SUM(v.others_cr_relevant_institutions) AS others_cr_relevant_institutions, " 
			+ "SUM(v.others_cr_to_battery) AS others_cr_to_battery,"
			+ " SUM(v.others_cr_to_defamation) AS others_cr_to_defamation," 
			+ " SUM(v.others_cr_to_divorce) AS others_cr_to_divorce, "
			+ "SUM(v.others_cr_to_legal_aid_service) AS others_cr_to_legal_aid_service," 
			+ " SUM(v.others_cr_to_medical_institutions) AS others_cr_to_medical_institutions,"
			+ " SUM(v.others_cr_to_minors) AS others_cr_to_minors, " 
			+ "SUM(v.others_cr_to_psycho_socio_counselling) AS others_cr_to_psycho_socio_counselling,"
			+ "SUM(v.others_cr_to_senior_citizen) AS others_cr_to_senior_citizen," 
			+ " SUM(v.others_cr_to_wages) AS others_cr_to_wages,"
			+ " SUM(v.others_cr_under47part2) AS others_cr_under47part2, " 
			+ "SUM(v.others_ds_medication_under47part2) AS others_ds_medication_under47part2,"
			+ "SUM(v.others_ds_under47part1) AS others_ds_under47part1,"
			+ "SUM(v.fir_registered_by_brahmin) AS fir_registered_by_brahmin,"
			+ "SUM(v.fir_registered_by_dalit) AS fir_registered_by_dalit,"
			+ "SUM(v.fir_registered_by_ethnic_minorities) AS fir_registered_by_ethnic_minorities,"
			+ "SUM(v.fir_registered_by_female) AS fir_registered_by_female,"
			+ "SUM(v.fir_registered_by_janajati) AS fir_registered_by_janajati,"
			+ "SUM(v.fir_registered_by_madhesi) AS fir_registered_by_madhesi,"
			+ "SUM(v.fir_registered_by_male) AS fir_registered_by_male,"
			+ "SUM(v.fir_registered_by_others) AS fir_registered_by_others,"
			+ "SUM(v.fir_registered_by_muslim) AS fir_registered_by_muslim,"
			+ "SUM(v.district_case_decided_by_court) AS district_case_decided_by_court,"
			+ "SUM(v.district_case_prosecuted_by_court) AS district_case_prosecuted_by_court,"
			+ "SUM(v.tip_case_decided_by_court) AS tip_case_decided_by_court,"
			+ "SUM(v.cr_about_tip) AS cr_about_tip,"
			+ "SUM(v.cr_about_polygamy) AS cr_about_polygamy,"
			+ "SUM(v.cr_about_child_marriage) AS cr_about_child_marriage,"
			+ "SUM(v.cr_about_forced_action) AS cr_about_forced_action,"
			+ "SUM(v.cr_about_forced_action_industry) AS cr_about_forced_action_industry,"
			+ "SUM(v.cr_about_unnatural_intercourse) AS cr_about_unnatural_intercourse,"
			+ "SUM(v.cr_about_child_sexual_abuse) AS cr_about_child_sexual_abuse,"
			+ "SUM(v.cr_about_sexual_abuse) AS cr_about_sexual_abuse,"
			+ "SUM(v.cr_about_accused_of_witchcraft) AS cr_about_accused_of_witchcraft,"
			+ "SUM(v.cr_about_domestic_violence) AS cr_about_domestic_violence,"
			+ "SUM(v.cr_about_tip_human_organ_transplantation) AS cr_about_tip_human_organ_transplantation,"
			+ "SUM(v.cr_about_forced_tip) AS cr_about_forced_tip,"
			+ "SUM(v.cr_about_beaten_and_miscarried) AS cr_about_beaten_and_miscarried,"
			+ "SUM(v.cr_about_throwing_alive_child) AS cr_about_throwing_alive_child,"
			+ "SUM(v.cr_about_kidnapping_and_rape) AS cr_about_kidnapping_and_rape,"
			+ "SUM(v.cr_about_duty_by_force) AS cr_about_duty_by_force,"
			+ "SUM(v.cr_about_abduction_and_duty) AS cr_about_abduction_and_duty"
			+ " from complaint_registration_report_view v " 
			+ "where v.fiscal_year = COALESCE(:fiscalYear,v.fiscal_year) "
			+ "and v.quarter = COALESCE(:quarter,v.quarter) "
			+ "and v.province_id = COALESCE(:provinceId,v.province_id) "
			+ "and v.district_id = COALESCE(:districtId,v.district_id) "
			+ "and v.municipality_id = COALESCE(:localLevelId,v.municipality_id) ")
	List<ComplaintRegistrationReport> getIndicatorReport(String fiscalYear, String quarter, String provinceId, String districtId,
			String localLevelId);


	@Query(nativeQuery = true, value = "select v.fiscal_year, v.province_id, v.province_desc_eng, "
			+ "v.province_desc_nep, "
			+ "SUM(v.district_case_decided_by_court) AS district_case_decided_by_court,"
			+ "SUM(v.district_case_prosecuted_by_court) AS district_case_prosecuted_by_court,"
			+ "SUM(v.tip_case_decided_by_court) AS tip_case_decided_by_court,"
			+ "SUM(v.tip_case_prosecuted_by_court) AS tip_case_prosecuted_by_court"
			+ " from complaint_registration_report_view v "
			+ " where v.fiscal_year = '2078-79' "
			+ " GROUP BY v.province_id")
	List<ComplaintRegistrationReport> getProvinceWiseReport();

	@Query(nativeQuery = true, value =  "select v.fiscal_year, v.province_id, v.province_desc_eng, "
			+ "v.province_desc_nep, v.district_id, v.district_desc_eng, " + "v.district_desc_nep, "
			+ "SUM(v.district_case_decided_by_court) AS district_case_decided_by_court,"
			+ "SUM(v.district_case_prosecuted_by_court) AS district_case_prosecuted_by_court,"
			+ "SUM(v.tip_case_decided_by_court) AS tip_case_decided_by_court,"
			+ "SUM(v.tip_case_prosecuted_by_court) AS tip_case_prosecuted_by_court"
			+ " from complaint_registration_report_view v "
			+ "WHERE v.province_id =:provinceId" 
			+ " AND v.fiscal_year = '2078-79' "
			+ " GROUP BY v.district_id")
	List<ComplaintRegistrationReport> getDistrictWiseReport(String provinceId);

	@Query(nativeQuery = true, value = "select v.fiscal_year, v.province_id, v.province_desc_eng, "
			+ "v.province_desc_nep, v.district_id, v.district_desc_eng, "
			+ "v.district_desc_nep, v.municipality_id, v.municipality_desc_eng," + "v.municipality_desc_nep, "
			+ "SUM(v.district_case_decided_by_court) AS district_case_decided_by_court,"
			+ "SUM(v.district_case_prosecuted_by_court) AS district_case_prosecuted_by_court,"
			+ "SUM(v.tip_case_decided_by_court) AS tip_case_decided_by_court,"
			+ "SUM(v.tip_case_prosecuted_by_court) AS tip_case_prosecuted_by_court"
			+ " from complaint_registration_report_view v "
			+ " WHERE v.district_id =:districtId" 
			+ " AND v.fiscal_year = '2078-79' "
			+ " GROUP BY v.municipality_id")
	List<ComplaintRegistrationReport> getMunicipalityWiseReport(String districtId);

}
