package com.pcs.itmis.report.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.pcs.itmis.report.entity.DisabledReport;
import com.pcs.itmis.report.entity.ReportEntity;

@Repository
public interface DisabledReportRepository extends JpaRepository<ReportEntity, Long> {

	@Query(nativeQuery = true, value = "select "
			+ "SUM(d.disabled_adult_ka) AS disabled_adult_ka, "
			+ "SUM(d.disabled_children_ka) AS disabled_children_ka, "
			+ "SUM(d.disabled_senior_citizen_ka) AS disabled_senior_citizen_ka, "
			+ "SUM(d.disabled_adult_kha) AS disabled_adult_kha, "
			+ "SUM(d.disabled_children_kha) AS disabled_children_kha, "
			+ "SUM(d.disabled_senior_citizen_kha) AS disabled_senior_citizen_kha, "
			+ "SUM(d.disabled_adult_ga) AS disabled_adult_ga, "
			+ "SUM(d.disabled_children_ga) AS disabled_children_ga, "
			+ "SUM(d.disabled_senior_citizen_ga) AS disabled_senior_citizen_ga, "
			+ "SUM(d.disabled_adult_gha) AS disabled_adult_gha, "
			+ "SUM(d.disabled_children_gha) AS disabled_children_gha, "
			+ "SUM(d.disabled_senior_citizen_gha) AS disabled_senior_citizen_gha "
			+ " from disabled_report_view d "
			+ " where d.fiscal_year = '2078-79' ")
	List<DisabledReport> getCumulativeDisabledReport();
	
	@Query(nativeQuery = true, value = "select d.fiscal_year, d.province_id, d.province_desc_eng, "
			+ "d.province_desc_nep, "
			+ "SUM(d.disabled_adult_ka) AS disabled_adult_ka, "
			+ "SUM(d.disabled_children_ka) AS disabled_children_ka, "
			+ "SUM(d.disabled_senior_citizen_ka) AS disabled_senior_citizen_ka, "
			+ "SUM(d.disabled_adult_kha) AS disabled_adult_kha, "
			+ "SUM(d.disabled_children_kha) AS disabled_children_kha, "
			+ "SUM(d.disabled_senior_citizen_kha) AS disabled_senior_citizen_kha, "
			+ "SUM(d.disabled_adult_ga) AS disabled_adult_ga, "
			+ "SUM(d.disabled_children_ga) AS disabled_children_ga, "
			+ "SUM(d.disabled_senior_citizen_ga) AS disabled_senior_citizen_ga, "
			+ "SUM(d.disabled_adult_gha) AS disabled_adult_gha, "
			+ "SUM(d.disabled_children_gha) AS disabled_children_gha, "
			+ "SUM(d.disabled_senior_citizen_gha) AS disabled_senior_citizen_gha "
			+ " from disabled_report_view d " 
			+ " where d.fiscal_year = '2078-79' "
			+ "GROUP BY d.province_id")
	List<DisabledReport> getProvinceWiseDisabledReport();

	@Query(nativeQuery = true, value = "select d.fiscal_year, d.province_id, d.province_desc_eng, "
			+ "d.province_desc_nep, d.district_id, d.district_desc_eng, "
			+ "d.district_desc_nep, "
			+ "SUM(d.disabled_adult_ka) AS disabled_adult_ka, "
			+ "SUM(d.disabled_children_ka) AS disabled_children_ka, "
			+ "SUM(d.disabled_senior_citizen_ka) AS disabled_senior_citizen_ka, "
			+ "SUM(d.disabled_adult_kha) AS disabled_adult_kha, "
			+ "SUM(d.disabled_children_kha) AS disabled_children_kha, "
			+ "SUM(d.disabled_senior_citizen_kha) AS disabled_senior_citizen_kha, "
			+ "SUM(d.disabled_adult_ga) AS disabled_adult_ga, "
			+ "SUM(d.disabled_children_ga) AS disabled_children_ga, "
			+ "SUM(d.disabled_senior_citizen_ga) AS disabled_senior_citizen_ga, "
			+ "SUM(d.disabled_adult_gha) AS disabled_adult_gha, "
			+ "SUM(d.disabled_children_gha) AS disabled_children_gha, "
			+ "SUM(d.disabled_senior_citizen_gha) AS disabled_senior_citizen_gha "
			+ " from disabled_report_view d " + "WHERE d.province_id =:provinceId" 
			+ " AND d.fiscal_year = '2078-79' "
			+ " GROUP BY d.district_id")
	List<DisabledReport> getDistrictWiseDisabledReport(@Param("provinceId") String provinceId);

	@Query(nativeQuery = true, value = "select d.fiscal_year, d.province_id, d.province_desc_eng, "
			+ "d.province_desc_nep, d.district_id, d.district_desc_eng, "
			+ "d.district_desc_nep, d.municipality_id, d.municipality_desc_eng,"
			+ "d.municipality_desc_nep, "
			+ "SUM(d.disabled_adult_ka) AS disabled_adult_ka, "
			+ "SUM(d.disabled_children_ka) AS disabled_children_ka, "
			+ "SUM(d.disabled_senior_citizen_ka) AS disabled_senior_citizen_ka, "
			+ "SUM(d.disabled_adult_kha) AS disabled_adult_kha, "
			+ "SUM(d.disabled_children_kha) AS disabled_children_kha, "
			+ "SUM(d.disabled_senior_citizen_kha) AS disabled_senior_citizen_kha, "
			+ "SUM(d.disabled_adult_ga) AS disabled_adult_ga, "
			+ "SUM(d.disabled_children_ga) AS disabled_children_ga, "
			+ "SUM(d.disabled_senior_citizen_ga) AS disabled_senior_citizen_ga, "
			+ "SUM(d.disabled_adult_gha) AS disabled_adult_gha, "
			+ "SUM(d.disabled_children_gha) AS disabled_children_gha, "
			+ "SUM(d.disabled_senior_citizen_gha) AS disabled_senior_citizen_gha "
			+ "from disabled_report_view d " + "WHERE d.district_id =:districtId" 
			+ " AND d.fiscal_year = '2078-79' "
			+ " GROUP BY d.municipality_id")
	List<DisabledReport> getMunicipalityWiseDisabledReport(@Param("districtId") String districtId);

	@Query(nativeQuery = true, value = "select "
			+ " SUM(v.disabled_id) AS disabled_id," 
			+ "SUM(v.disabled_adult_receiving_services) AS disabled_adult_receiving_services,"
			+ " SUM(v.disabled_children_receiving_services) AS disabled_children_receiving_services,"
			+ " SUM(v.disabled_senior_citizen_receiving_services) AS disabled_senior_citizen_receiving_services, " 
			+ "SUM(v.disabled_male_receiving_services) AS disabled_male_receiving_services,"
			+ " SUM(v.disabled_female_receiving_services) AS disabled_female_receiving_services," 
			+ " SUM(v.disabled_others_receiving_services) AS disabled_others_receiving_services, "
			+ "SUM(v.autism_receiving_services) AS autism_receiving_services," 
			+ " SUM(v.deaf_blind_receiving_services) AS deaf_blind_receiving_services,"
			+ " SUM(v.intellectually_disabled_receiving_services) AS intellectually_disabled_receiving_services,"
			+ " SUM(v.mental_disability_receiving_services) AS mental_disability_receiving_services,"
			+ " SUM(v.multiple_receiving_services) AS multiple_receiving_services,"
			+ " SUM(v.physically_disabled_receiving_services) AS physically_disabled_receiving_services,"
			+ " SUM(v.speech_and_hearing_receiving_services) AS speech_and_hearing_receiving_services,"
			+ " SUM(v.hemophelia_receiving_services) AS hemophelia_receiving_services,"
			+ " SUM(v.visually_impaired_receiving_services) AS visually_impaired_receiving_services,"
			+ " SUM(v.hearing_impaired_receiving_services) AS hearing_impaired_receiving_services,"
			+ " SUM(v.per_of_dis_peop_job) AS per_of_dis_peop_job,"
			+ " SUM(v.male_rec_skill_training) AS male_rec_skill_training,"
			+ " SUM(v.female_rec_skill_training) AS female_rec_skill_training,"
			+ " SUM(v.others_rec_skill_training) AS others_rec_skill_training,"
			+ " SUM(v.tot_disabled_rehab_center) AS tot_disabled_rehab_center,"
			+ " AVG(v.budget_allocated_for_disabled) AS budget_allocated_for_disabled,"
			+ " AVG(v.disabled_affected_by_calamities) AS disabled_affected_by_calamities,"
			
			+ "SUM(v.disabled_female_ka) AS disabled_female_ka,"
			+ "SUM(v.disabled_female_receivingssa_ka) AS disabled_female_receivingssa_ka," 
			+ "SUM(v.disabled_male_ka) AS disabled_male_ka," 
			+ " SUM(v.disabled_male_receivingssa_ka) AS disabled_male_receivingssa_ka,"
			+ " SUM(v.disabled_others_ka) AS disabled_others_ka, " 
			+ "SUM(v.disabled_others_receivingssa_ka) AS disabled_others_receivingssa_ka,"
			+ "SUM(v.disabled_adult_ka) AS disabled_adult_ka,"
			+ "SUM(v.disabled_adult_receivingssa_ka) AS disabled_adult_receivingssa_ka,"
			+ "SUM(v.disabled_children_ka) AS disabled_children_ka,"
			+ "SUM(v.disabled_children_receivingssa_ka) AS disabled_children_receivingssa_ka,"
			+ "SUM(v.disabled_senior_citizen_ka) AS disabled_senior_citizen_ka,"
			+ "SUM(v.disabled_senior_citizen_receivingssa_ka) AS disabled_senior_citizen_receivingssa_ka,"
			+ "SUM(v.autism_ka) AS autism_ka,"
			+ "SUM(v.autism_receivingssa_ka) AS autism_receivingssa_ka,"
			+ "SUM(v.deaf_blind_ka) AS deaf_blind_ka,"
			+ "SUM(v.deaf_blind_receivingssa_ka) AS deaf_blind_receivingssa_ka,"
			+ "SUM(v.hemophelia_ka) AS hemophelia_ka,"
			+ "SUM(v.hemophelia_receivingssa_ka) AS hemophelia_receivingssa_ka,"
			+ "SUM(v.intellectually_disabled_ka) AS intellectually_disabled_ka,"
			+ "SUM(v.intellectually_disabled_receivingssa_ka) AS intellectually_disabled_receivingssa_ka,"
			+ "SUM(v.mental_disability_ka) AS mental_disability_ka,"
			+ "SUM(v.mental_disability_receivingssa_ka) AS mental_disability_receivingssa_ka,"
			+ "SUM(v.multiple_ka) AS multiple_ka,"
			+ "SUM(v.multiple_receivingssa_ka) AS multiple_receivingssa_ka,"
			+ "SUM(v.physically_disabled_ka) AS physically_disabled_ka,"
			+ "SUM(v.physically_disabled_receivingssa_ka) AS physically_disabled_receivingssa_ka,"
			+ "SUM(v.speech_and_hearing_ka) AS speech_and_hearing_ka,"
			+ "SUM(v.speech_and_hearing_receivingssa_ka) AS speech_and_hearing_receivingssa_ka,"
			+ "SUM(v.visually_impaired_ka) AS visually_impaired_ka,"
			+ "SUM(v.visually_impaired_receivingssa_ka) AS visually_impaired_receivingssa_ka,"
			+ "SUM(v.hearing_impaired_ka) AS hearing_impaired_ka,"
			+ "SUM(v.hearing_impaired_receivingssa_ka) AS hearing_impaired_receivingssa_ka,"
			
			+ "SUM(v.disabled_female_kha) AS disabled_female_kha,"
			+ "SUM(v.disabled_female_receivingssa_kha) AS disabled_female_receivingssa_kha," 
			+ "SUM(v.disabled_male_kha) AS disabled_male_kha," 
			+ " SUM(v.disabled_male_receivingssa_kha) AS disabled_male_receivingssa_kha,"
			+ " SUM(v.disabled_others_kha) AS disabled_others_kha, " 
			+ "SUM(v.disabled_others_receivingssa_kha) AS disabled_others_receivingssa_kha,"
			+ "SUM(v.disabled_adult_kha) AS disabled_adult_kha,"
			+ "SUM(v.disabled_adult_receivingssa_kha) AS disabled_adult_receivingssa_kha,"
			+ "SUM(v.disabled_children_kha) AS disabled_children_kha,"
			+ "SUM(v.disabled_children_receivingssa_kha) AS disabled_children_receivingssa_kha,"
			+ "SUM(v.disabled_senior_citizen_kha) AS disabled_senior_citizen_kha,"
			+ "SUM(v.disabled_senior_citizen_receivingssa_kha) AS disabled_senior_citizen_receivingssa_kha,"
			+ "SUM(v.autism_kha) AS autism_kha,"
			+ "SUM(v.autism_receivingssa_kha) AS autism_receivingssa_kha,"
			+ "SUM(v.deaf_blind_kha) AS deaf_blind_kha,"
			+ "SUM(v.deaf_blind_receivingssa_kha) AS deaf_blind_receivingssa_kha,"
			+ "SUM(v.hemophelia_kha) AS hemophelia_kha,"
			+ "SUM(v.hemophelia_receivingssa_kha) AS hemophelia_receivingssa_kha,"
			+ "SUM(v.intellectually_disabled_kha) AS intellectually_disabled_kha,"
			+ "SUM(v.intellectually_disabled_receivingssa_kha) AS intellectually_disabled_receivingssa_kha,"
			+ "SUM(v.mental_disability_kha) AS mental_disability_kha,"
			+ "SUM(v.mental_disability_receivingssa_kha) AS mental_disability_receivingssa_kha,"
			+ "SUM(v.multiple_kha) AS multiple_kha,"
			+ "SUM(v.multiple_receivingssa_kha) AS multiple_receivingssa_kha,"
			+ "SUM(v.physically_disabled_kha) AS physically_disabled_kha,"
			+ "SUM(v.physically_disabled_receivingssa_kha) AS physically_disabled_receivingssa_kha,"
			+ "SUM(v.speech_and_hearing_kha) AS speech_and_hearing_kha,"
			+ "SUM(v.speech_and_hearing_receivingssa_kha) AS speech_and_hearing_receivingssa_kha,"
			+ "SUM(v.visually_impaired_kha) AS visually_impaired_kha,"
			+ "SUM(v.visually_impaired_receivingssa_kha) AS visually_impaired_receivingssa_kha,"
			+ "SUM(v.hearing_impaired_kha) AS hearing_impaired_kha,"
			+ "SUM(v.hearing_impaired_receivingssa_kha) AS hearing_impaired_receivingssa_kha,"

			+ "SUM(v.disabled_female_ga) AS disabled_female_ga,"
			+ "SUM(v.disabled_female_receivingssa_ga) AS disabled_female_receivingssa_ga," 
			+ "SUM(v.disabled_male_ga) AS disabled_male_ga," 
			+ " SUM(v.disabled_male_receivingssa_ga) AS disabled_male_receivingssa_ga,"
			+ " SUM(v.disabled_others_ga) AS disabled_others_ga, " 
			+ "SUM(v.disabled_others_receivingssa_ga) AS disabled_others_receivingssa_ga,"
			+ "SUM(v.disabled_adult_ga) AS disabled_adult_ga,"
			+ "SUM(v.disabled_adult_receivingssa_ga) AS disabled_adult_receivingssa_ga,"
			+ "SUM(v.disabled_children_ga) AS disabled_children_ga,"
			+ "SUM(v.disabled_children_receivingssa_ga) AS disabled_children_receivingssa_ga,"
			+ "SUM(v.disabled_senior_citizen_ga) AS disabled_senior_citizen_ga,"
			+ "SUM(v.disabled_senior_citizen_receivingssa_ga) AS disabled_senior_citizen_receivingssa_ga,"
			+ "SUM(v.autism_ga) AS autism_ga,"
			+ "SUM(v.autism_receivingssa_ga) AS autism_receivingssa_ga,"
			+ "SUM(v.deaf_blind_ga) AS deaf_blind_ga,"
			+ "SUM(v.deaf_blind_receivingssa_ga) AS deaf_blind_receivingssa_ga,"
			+ "SUM(v.hemophelia_ga) AS hemophelia_ga,"
			+ "SUM(v.hemophelia_receivingssa_ga) AS hemophelia_receivingssa_ga,"
			+ "SUM(v.intellectually_disabled_ga) AS intellectually_disabled_ga,"
			+ "SUM(v.intellectually_disabled_receivingssa_ga) AS intellectually_disabled_receivingssa_ga,"
			+ "SUM(v.mental_disability_ga) AS mental_disability_ga,"
			+ "SUM(v.mental_disability_receivingssa_ga) AS mental_disability_receivingssa_ga,"
			+ "SUM(v.multiple_ga) AS multiple_ga,"
			+ "SUM(v.multiple_receivingssa_ga) AS multiple_receivingssa_ga,"
			+ "SUM(v.physically_disabled_ga) AS physically_disabled_ga,"
			+ "SUM(v.physically_disabled_receivingssa_ga) AS physically_disabled_receivingssa_ga,"
			+ "SUM(v.speech_and_hearing_ga) AS speech_and_hearing_ga,"
			+ "SUM(v.speech_and_hearing_receivingssa_ga) AS speech_and_hearing_receivingssa_ga,"
			+ "SUM(v.visually_impaired_ga) AS visually_impaired_ga,"
			+ "SUM(v.visually_impaired_receivingssa_ga) AS visually_impaired_receivingssa_ga,"
			+ "SUM(v.hearing_impaired_ga) AS hearing_impaired_ga,"
			+ "SUM(v.hearing_impaired_receivingssa_ga) AS hearing_impaired_receivingssa_ga,"

			+ "SUM(v.disabled_female_gha) AS disabled_female_gha,"
			+ "SUM(v.disabled_female_receivingssa_gha) AS disabled_female_receivingssa_gha," 
			+ "SUM(v.disabled_male_gha) AS disabled_male_gha," 
			+ " SUM(v.disabled_male_receivingssa_gha) AS disabled_male_receivingssa_gha,"
			+ " SUM(v.disabled_others_gha) AS disabled_others_gha, " 
			+ "SUM(v.disabled_others_receivingssa_gha) AS disabled_others_receivingssa_gha,"
			+ "SUM(v.disabled_adult_gha) AS disabled_adult_gha,"
			+ "SUM(v.disabled_adult_receivingssa_gha) AS disabled_adult_receivingssa_gha,"
			+ "SUM(v.disabled_children_gha) AS disabled_children_gha,"
			+ "SUM(v.disabled_children_receivingssa_gha) AS disabled_children_receivingssa_gha,"
			+ "SUM(v.disabled_senior_citizen_gha) AS disabled_senior_citizen_gha,"
			+ "SUM(v.disabled_senior_citizen_receivingssa_gha) AS disabled_senior_citizen_receivingssa_gha,"
			+ "SUM(v.autism_gha) AS autism_gha,"
			+ "SUM(v.autism_receivingssa_gha) AS autism_receivingssa_gha,"
			+ "SUM(v.deaf_blind_gha) AS deaf_blind_gha,"
			+ "SUM(v.deaf_blind_receivingssa_gha) AS deaf_blind_receivingssa_gha,"
			+ "SUM(v.hemophelia_gha) AS hemophelia_gha,"
			+ "SUM(v.hemophelia_receivingssa_gha) AS hemophelia_receivingssa_gha,"
			+ "SUM(v.intellectually_disabled_gha) AS intellectually_disabled_gha,"
			+ "SUM(v.intellectually_disabled_receivingssa_gha) AS intellectually_disabled_receivingssa_gha,"
			+ "SUM(v.mental_disability_gha) AS mental_disability_gha,"
			+ "SUM(v.mental_disability_receivingssa_gha) AS mental_disability_receivingssa_gha,"
			+ "SUM(v.multiple_gha) AS multiple_gha,"
			+ "SUM(v.multiple_receivingssa_gha) AS multiple_receivingssa_gha,"
			+ "SUM(v.physically_disabled_gha) AS physically_disabled_gha,"
			+ "SUM(v.physically_disabled_receivingssa_gha) AS physically_disabled_receivingssa_gha,"
			+ "SUM(v.speech_and_hearing_gha) AS speech_and_hearing_gha,"
			+ "SUM(v.speech_and_hearing_receivingssa_gha) AS speech_and_hearing_receivingssa_gha,"
			+ "SUM(v.visually_impaired_gha) AS visually_impaired_gha,"
			+ "SUM(v.visually_impaired_receivingssa_gha) AS visually_impaired_receivingssa_gha,"
			+ "SUM(v.hearing_impaired_gha) AS hearing_impaired_gha,"
			+ "SUM(v.hearing_impaired_receivingssa_gha) AS hearing_impaired_receivingssa_gha"

			+ " from disabled_report_view v " 
			+ "where v.fiscal_year = COALESCE(:fiscalYear,v.fiscal_year) "
			+ "and v.quarter = COALESCE(:quarter,v.quarter) "
			+ "and v.province_id = COALESCE(:provinceId,v.province_id) "
			+ "and v.district_id = COALESCE(:districtId,v.district_id) "
			+ "and v.municipality_id = COALESCE(:localLevelId,v.municipality_id) ")
	List<DisabledReport> getIndicatorReport(String fiscalYear, String quarter, String provinceId, String districtId,
			String localLevelId);


}
