server:
  port: 9006
  
spring:
  application:
    name: CHILD-HOME-SERVICE
    
security:
  oauth2:
    resource:
     token-info-uri: http://localhost:8087/security/oauth/check_token
    client:
     client-id: itmis
     client-secret: itmis  
     
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://localhost:8761/eureka/
  instance:
    hostname: localhost